# ----------- CONFIGURABLE START -----------
title:            "gqjia"
description:      "I walk in the rain."
url:              https://gqjia.github.io  # Site url, without a slash at the end.
signoff:          "gqjia" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            true # Turn on twitter and facebook share buttons

links:
  - name:         Posts
    url:          /
    external:     false
  - name:         Archive
    url:          /archive
    external:     false
  - name:         About me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

# Comments (Giscus)
giscus:
  repo:             "gqjia/gqjia.github.io" # 已自动填充
  repo_id:          "MDEwOlJlcG9zaXRvcnkxNTM4ODQwOTI=" # 需手动获取
  category:         "Announcements" # 推荐使用 Announcements
  category_id:      "DIC_kwDOCSwVvM4Cz_cw" # 需手动获取
  mapping:          "pathname"
  input_position:   "top"
  theme:            "light"
  lang:             "zh-CN"

permalink:        /posts/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - values:
      layout: "default"
