# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liu-Cheng Xu
email: xuliuchengxlc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The world is indeed a stage and we are merely players.
baseurl: /blog-cn  # the subpath of your site, e.g. /blog
lang: "en"
url:  # the base hostname & protocol for your site
twitter_username:
github_username:  liuchengxu
disqus_username:
google_analytics: UA-73260325-3

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
